### ISSUE TITLE
BadRequest / 400 issue after batch processes

### ISSUE THREAD

**Issue by goodbayscott** [DouglasCAyers/sfdx-mass-action-scheduler#1]
everything for setup went swimmingly, and it seems to be running smoothly other than there being an error when trying to run the action (based on a process). Not much info is given other than the "BadRequest" unknown exception typical jargon.  My user has the force.com flow user enabled and the user selected is the same one throughout.  Any ideas?

Here's a shot of the Apex log:
![screenshot 2018-01-01 at 6 27 59 pm](https://user-images.githubusercontent.com/5986616/34470094-2f9b58b4-ef22-11e7-8bcd-4ee4a6e4e888.png)

The errors also show up in the Mass Action Log:
![screenshot 2018-01-01 at 6 35 50 pm](https://user-images.githubusercontent.com/5986616/34470120-a9910de4-ef22-11e7-9625-8bcec83c03d5.png)

**Comment by DouglasCAyers** [comment]
Hi Scott,

Thanks for the detailed report. Glad the setup went well for you!

I’m trying to think what the issue is. Is the user for the Named Credential an admin? If no, please try as an admin to see if the problem may be access/permission based. 

Another thing to try is to test with a very simple Process Builder that simply posts a Chatter message to the record. That is to say, remove your specific logic from the equation as we try to narrow down where the issue might be. 

Another thing to check is confirm the list view field “Id” used in the field mapping is non-blank/non-null ID of the object type your process operates on. I’m wondering if that might not be the list view’s own id and there may be another field to choose that’s called “account id” or something?

Doug

**Comment by DouglasCAyers** [comment]
Hi @goodbayscott, have you had a chance to look into this further? Any luck?

**Comment by DouglasCAyers** [comment]
I've just [released version 1.5](https://github.com/DouglasCAyers/sfdx-mass-action-scheduler#packaged-release-history) of the app that introduces `Mass_Action_Log__c.Long_Message__c` long text field that will capture the entire exception message. Please upgrade to that version and hopefully can learn more details about what that error message is trying to tell us.

Thanks!

**Comment by goodbayscott** [comment]
Hey thanks for getting back to me, gmail apparently has resorted my emails
and I missed this. Been a busy week back on top of that!

I'm running thru the tests you've sent over now (after an update), will
report back asap. Thanks for your attention on this, and sorry I missed the
webinar - had a family emergency come up and haven't been in the office
much this week, so if you've got a recording I'd love to watch it some time.

Thanks,
Scott M.

*Scott Manning* | Good Bay Co.
*E: scott@goodbay.co <scott@goodbay.co> | P: (657) 229.2205
<(657)%20229-2205>*
goodbay.co

**Comment by DouglasCAyers** [comment]
Hi @goodbayscott, haven't heard back from you in a few months. I'm going to close this issue assuming the problem is resolved. If not, please comment back and I'll re-open. Thanks for your interest in Mass Action Scheduler!
