### ISSUE TITLE
Specify the order of schedules

### ISSUE THREAD

**Issue by danhowellnz** [douglascayers/sfdx-mass-action-scheduler#12]
This looks awesome! I haven't tried it out yet. One idea that I built into my tool was te ability to choose the order in which actions run. 

I used an interface instead of cron jobs as people don't know how to use crons (I have to google it every time myself). I added a sort order field. Then in the batch finish it ran the next schedule. This was important to stop lock row errors and when running automation in a specific order

**Comment by DouglasCAyers** [comment]
Thanks for the feedback and suggestion @danhowellnz!

**Comment by DouglasCAyers** [comment]
This will be easier to do in the next release I'm currently working on. Introducing a unique name on the configuration records that can be referenced via the invocable apex action to Run Mass Actions.

There will also be a new last run date/time field so that you can define Process Builders on the `Mass_Action_Configuration__c` object, monitor for that date/time to change, and that lets you know that one of the runs has completed, so use process builder to enqueue the next action. You can chain as many as you'd like. I'll write up a more formal documentation and how-to for the wiki once this goes live. 

![image](https://user-images.githubusercontent.com/4142577/40296021-1c083dd4-5ca1-11e8-9cf7-8daa7ebb697e.png)

**Comment by danhowellnz** [comment]
That's great. 

We can also get row lock on things firing at the same time for the average user. That's why my version went through each schedule in sequence. 

So there is never two batches running in parallel that start at the same time.
