### ISSUE TITLE
Working great for me, but no run button for another user

### ISSUE THREAD

**Issue by annacrotty** [DouglasCAyers/sfdx-mass-action-scheduler#19]
I hope that all my questions and issues are useful testing rather than just super annoying.  

I've been using Mass Action Scheduler very successfully at several orgs, and this week showed another user how to use a config I had set up.  He doesn't see the run button, even though he has the same user profile that I do.  I assume there's a Visualforce component somewhere that he needs access to, but I can't figure out what and where?

Thanks so much,
Anna

**Comment by DouglasCAyers** [comment]
Hi @annacrotty,

I'm glad that the app is working well for you!

The "Run" button is just custom button added to the Mass Action Configuration page layout. The only thing I can think of if the user doesn't see the button is that they are not viewing the the correct page layout, which is strange because there should only be one layout and even more strange if you see it and they don't.

Could you provide screen shots of what you see and what the other user sees?

To confirm, the other user is in Lightning Experience and not Classic, correct?

Thanks!

**Comment by annacrotty** [comment]
I think I see the problem - it looks like he sent me a screen shot that didn't include the whole screen and so I didn't realize that he hadn't chosen a configuration yet...my apologies!  

I am planning to write up a blog post on all the cool things we're doing with it.  I think people haven't appreciated how earth shakingly awesome it is to be able to efficiently deal with fringe cases without having to touch every record in a batch job!

**Comment by DouglasCAyers** [comment]
Thanks for the update @annacrotty. Glad you were able to figure it out =)

And thank you very much for the kind feedback. I look forward to reading about the great solutions you're able to build out with Mass Action Scheduler =)
