### ISSUE TITLE
Error on larger jobs

### ISSUE THREAD

**Issue by huyghet** [douglascayers/sfdx-mass-action-scheduler#37]
Hi Douglas,  first off, I gotta give thanks for your work and applications.  They have been huge time and money savers for us, especially those of us who work in the non-profit world.   

I do have one question.  I recently added the Mass Scheduler, and seem to be having issues on larger jobs.  We use the NPSP, and want to create two records from a GAU Allocation at a set time every night.   Jitterbit then takes those files, does a transformation, and prepares an upload file (outside of SF) for NetSuite.   Those records are created when the Mass Scheduler triggers a Process Flow.   The Process Flow runs off a simple GAU Allocation report with a specific status, and creates the two records from GAU values, and a couple formulas. 

Everything seems to be configured correctly, in that I can get the output file I want most of the time.   But I have been getting errors from the Scheduler when trying to run on 500+ GAU Allocations with batch size as low as 10.   Errors appear to be locking errors, not tied to any specific validation, or coding error.  DO you have any guidance.  The screen shot is below.  This job had 500 records at a 25 record batch size.  It created 975 of the intended 1000 (500x2) records. 

Thanks again,
Todd

![error screenshot](https://user-images.githubusercontent.com/40129084/41196683-cdfd6cd0-6c14-11e8-96ba-c012bb9b63e7.JPG)

**Comment by douglascayers** [comment]
Hi @huyghet, glad you're enjoying my apps and Mass Action Scheduler. Thank you for the kind feedback!

Regarding the errors, unfortunately the API does not provide back the meaningful error message of what actually is going wrong, just "an error occurred".

Are you receiving the emails from Process Builder / Flow with the specific details of the failure? You mentioned "Errors appear to be locking errors" so wondering where you got tipped off that it may be locking related.

In the Summer '18 release, you can [add yourself to the Apex Exception Email](https://releasenotes.docs.salesforce.com/en-us/summer18/release-notes/rn_forcecom_flow_email_apex.htm) list to ensure you get notified with the email of the specific errors. Those errors will help in troubleshooting the root cause.

Thanks,

Doug

**Comment by huyghet** [comment]
Hello, thanks for the quick reply.  I think we can close this issue.  I have been receiving generic locking errors on a lot of my my bulk processes, and think I was too quick to assume it was responsible here.  But it was indeed an error of my fault on a process flow that took a unique instance to trigger it.    The Mass Action Scheduler is working exactly as laid out.  Thanks again for your help!  I'll definitely be visiting here often.

**Comment by douglascayers** [comment]
Glad it's working for you! Those locking errors can be annoying
