### ISSUE TITLE
Sending Mass Email with Mass Action Scheduler

### ISSUE THREAD

**Issue by ApexUniverse** [douglascayers/sfdx-mass-action-scheduler#38]
Hi Doug,

Great App, thanks.

Please could you advise on the best way to use this App to send a monthly email to a set of users?

If the email body needs to include a table/list of information?

Thanks

**Comment by douglascayers** [comment]
Hi @ApexUniverse, thanks for taking an interest in Mass Action Scheduler and for the kind words.

For sending an email monthly, you could create a list view of users and then set a schedule frequency of say 1:00 AM, on the 1st of the month, every month. The action could be an Email Alert.

For formatting the email content as a table, if you have trouble getting this to look how you want with Custom Email Template, then you may try using a Visualforce Email Template, which lets you use HTML and Visualforce markup to define a table/list of information.

**Comment by ApexUniverse** [comment]
Hi @douglascayers , Thanks for responding.

I don't think I communicated very well, apologies.

The table/list of information is dynamic based on the recipient.

What is the best way to approach this?

**Comment by douglascayers** [comment]
Use a Visualforce email template with your email alert because that lets you leverage code to identify how the data for the table needs to change on a per recipient basis. 

Or, if that table of data could instead be a link in the email to a report or something in Salesforce then you can avoid using code for the email template at the tradeoff that users don’t see the info in the email immediately.

**Comment by SalesforceBobLightning** [comment]
Hi @douglascayers 

Thanks for the advise RE email alerts

If I want to send an email to 500 person accounts every day, and the email contains a list of their appointments for that day. What data source should I use? 

If I create a report of person account with appointments, won't MAS (mass action scheduler) send an email for each record?

Or if I create a VF component to display the appointment list in the VF email template, I will hit a governor limit because the component controller does too many SOQL queries...

What are your thoughts on the base way to achieve this using MAS?

**Comment by douglascayers** [comment]
@SalesforceBobLightning, I would try the following:

1. Create a report (or list view) that gives you the unique Contact or Lead or Person Account records to whom you want to send the email. The report should only have a row per unique email address, do not do a "Person Account with Appointments" because then the report will have a row per appointment and end up sending an email per appointment rather than per person.

2. The Visualforce email template would use an Apex controller to query for the appointments for that recipient, not query for all recipients.

3. If you experience governor limits, then on your Mass Action Configuration record, click the "Quick Edit" button to modify the batch size down from 200 to something less, maybe 100 or 50 or less until you don't hit the governor limit.

Hope that helps :)
