### ISSUE TITLE
Permission Set

### ISSUE THREAD

**Issue by Rowe89** [douglascayers/sfdx-mass-action-scheduler#42]
Went through steps loading into full sandbox but it did not create a permission set.

**Comment by douglascayers** [comment]
Hi @Rowe89,

Can you confirm that the package actually installed? I ask because [people have reported](https://success.salesforce.com/0D53A00003o4Gpi) that due to known issue [W-5394323](https://salesforce.stackexchange.com/a/230604/987) that installing managed packages into sandboxes are failing. I wonder if you're in the same boat.

The only other workarounds are to either deploy the metadata from GitHub directly, or deploy into production (or try out in a free developer edition org).

**Comment by douglascayers** [comment]
Bug W-5394323 has since been fixed by Salesforce engineering teams. Please let me know if you encounter this again. Root cause was that the namespace cache for looking up Lightning components after installing a managed package was stale and so didn't have the new components. The new process is to invalidate the cache so the new components will be found.
