### ISSUE TITLE
MAS doesn't seem to kick off action

### ISSUE THREAD

**Issue by annacrotty** [douglascayers/sfdx-mass-action-scheduler#43]
I'm experimenting with something that is likely to not work at some point (full disclosure!) but I admit I'm running into a different problem than I expected.

I've got a report with one opportunity in it.
I've got a quick action on the opportunity.  If I click on that quick action from the opportunity page for that one opportunity, the field updates as I'd expect.  
I've got Mass Action Scheduler set to take that report with one record and run that action on it.  

If I do a manual run of the mass action configuration, the job completes, and there are no errors, but the field doesn't update.  I'm not getting any emailed error messages, and I've checked the developer logs and don't see any errors either.  

I'm mystified about what is happening.  Honestly I'd expected an error (the quick action updates a field based on a formula that is so ridiculous I've actually named it "insanity.") but I didn't expect it to succeed from the opportunity record page but not the mass action configuration.

I am sure that I'm doing something wrong, but I'm afraid I'm out of ideas.  If you've got suggestions of other things I can check, I'd be grateful!

FWIW, in this same Salesforce org I do have several mass action configurations running like a charm with no problems, so I think it is fair to eliminate the basic mass action setup as a culprit.  (I think?)

**Comment by douglascayers** [comment]
Hi Anna, glad to hear you’re getting good use out of Mass Action Scheduler. 

For this opportunity quick action, would you please share screen shots of the action’s field layout and where you’ve defined the default values for the field update on the action, and screen shot in Mass Action Configuration wizard of the field mapping step?

Thanks

**Comment by annacrotty** [comment]
Hi Doug,
Thanks so much for the response, especially on a weekend!

I'm including these screenshots.  It is just the one predefined field for the action, and the formula is so long it won't show up in a single screen.  I've just blurred the text that I'm inserting to protect the identity of the organization with a business process that would inspire such a monstrosity.  ;-)

![default field values blurred](https://user-images.githubusercontent.com/7375753/45267344-797cad80-b41f-11e8-848c-1f3afcdf4306.jpg)
![field mapping](https://user-images.githubusercontent.com/7375753/45267345-797cad80-b41f-11e8-9fd6-a6e6b2276fdb.png)
![action layout](https://user-images.githubusercontent.com/7375753/45267346-7a154400-b41f-11e8-9d34-b73a110bf737.png)

**Comment by douglascayers** [comment]
Hi @annacrotty,

I did a test and I was able to perform a field update on Account record using a "Update Record" quick action using predefined field value using IF formula and no fields on the layout. In my test, the record was updated accordingly (screen shot below).

For troubleshooting, in order of simplest to do to a bit more effort, please try:

1. Confirm that the Mass Action record is **Active**. It probably is based on your comments, but if it were inactive that would definitely be a cause for the record not updating.

2. Simplify the formula to something very trivial, perhaps a static value like "test", to confirm that the Mass Action updates the record. If it does with the simplified formula, then the issue may be with the formula -- and perhaps not a problem but perhaps it's resolving to a different value than what you're expecting.

3. Check that there aren't other triggers/processes/workflow rules/etc running that may be modifying the field. I bring this up because in my org I did have a process builder overwriting the field I was testing (I have bad habit of always updating the `Account.Description` field so high chances of conflicts).

![image](https://user-images.githubusercontent.com/4142577/45327911-3144b480-b51f-11e8-9618-05cf339f75a1.png)

**Comment by annacrotty** [comment]
Thank you!  I'm excited about the new release.  

As so often happens with such complex requests, the person requesting it changed his mind after I did this work, and so I haven't pursued the issue.  I'm going to close this - MAS continues to work perfectly for me in many situations!

**Comment by douglascayers** [comment]
Glad to hear both the complex request went away (hopefully 😉) and that MAS is still working out well for you.
