### ISSUE TITLE
Error with scheduled action

### ISSUE THREAD

**Issue by LCurran1006** [douglascayers/sfdx-mass-action-scheduler#47]
Hi! I am setting up a system for a local nonprofit and getting an error for one of my actions. I want to re-check a checkbox on the 1st day of every month, and set up a simple Action in the Account object. I get the error below and the action isn't properly working. My report is set up to select ALL Accounts that are "Active Food Bank Clients" (nondependent on if the checkbox is already checked or not). Do you have any tips for how I can fix this? Thanks so much - I'm excited about this app!

Error: System.HttpResponse[Status=Bad Request, StatusCode=400]
[{"actionName":"Account.Mass_Update_Commodities_Check","errors":[{"statusCode":"INVALID_TYPE_ON_FIELD_IN_RECORD","message":"Collect Commodities Signature: value not of required type: false","f

**Comment by LCurran1006** [comment]
Hi @douglascayers it is set up using a Quick Action, not a flow.

**Comment by douglascayers** [comment]
Gotcha. If you’re trying to pass in a checkbox field value (true/false) there is a limitation I think that the API sends that data over as text, not a Boolean (or vice versa, either way it’s not the expected data type). 

Since the Salesforce platform is determining the data type being sent in the API, I think you’d have to use a workaround and map a non checkbox field over THEN use extra automation to make a field update based on that. Definitely not ideal but I’m not sure what else to do at the moment.

**Comment by douglascayers** [comment]
For example, instead of yor target being a Quick Action you could use a Flow target. The Flow input variable type to be Text and use a Decision element to do a Record Update Action is the text variable is “true” or “false”.

**Comment by douglascayers** [comment]
Hi @LCurran1006,  I've opened a new [enhancement](https://github.com/douglascayers/sfdx-mass-action-scheduler/issues/64) request to track checkbox/boolean field support. A few other people have reported similar problems so this new issue will help me track and communicate progress towards it in one central spot. Thanks for your interest in Mass Action Scheduler!
