### ISSUE TITLE
Professional Edition

### ISSUE THREAD

**Issue by SalesforceBobLightning** [douglascayers/sfdx-mass-action-scheduler#51]
Will this work on Professional Edition?

**Comment by douglascayers** [comment]
Hi @SalesforceBobLightning,

Unfortunately, I don't believe this will work in Professional Edition because the app requires Apex and use of the REST API, which might not be enabled in Professional Edition orgs.

Although my app is available to be installed as a managed package, it has to be a "certified" app for Professional Edition, and I don't have the time or resources to go through that process right now. Sorry :(
