### ISSUE TITLE
Trying to create a Mass Action Mapping

### ISSUE THREAD

**Issue by bpurcell89** [douglascayers/sfdx-mass-action-scheduler#65]
Doug,
Love the concept of this app, it solves a glaring business need for us. I have been trying to install and use correctly, but I have run into a number of issues. I had previously been unable to choose an action, but today I noticed you released an update that would bypass the need for named credentials. I uninstalled the package and reinstalled the new version.

I am now having another issue when trying to create a new mass action mapping. Check out this screenshot;
![screen shot 2019-01-02 at 2 31 01 pm](https://user-images.githubusercontent.com/16195070/50615963-6b094480-0e9b-11e9-9652-0ceed5931166.png)
I am prompted to either link to a previous config, or create a new mass action configuration. Since I don't have any created, I went to create a new record but I am just linked back to the same screen and unable to create anything. What should I do? Have I installed this incorrectly?

Thanks,
Brian Purcell

**Comment by bpurcell89** [comment]
Strange, I just went and tried to set up the process again and it appears to be working!

**Comment by douglascayers** [comment]
Hi @bpurcell89, thanks for your interest in Mass Action Scheduler.

Per the earlier screen shot, it looks like you were accidentally on the “Mass Action Mapping” object instead of “Mass Action Configuration”.  Per you update, sounds like you eventually got to the right page. Sorry for any confusion / lack of intuitive UI there with such similar object names. 

You should only ever have to go to the “Mass Action Configuration” object and use the “Configure” wizard to create your configuration and mappings. I don’t recommend editing the record directly (eg data loader, Classic UI, etc) or it’s mappings related list as it could cause a config record to not work and you’d need to recreate it.
